### ISSUE TITLE
Frank -> Dyfrig -> Freya ?

### ISSUE THREAD

**Issue by wallymathieu** [panesofglass/TodoBackendFSharp#7]
Hi! Noticed that https://www.todobackend.com/ labels this repo as a todo backend implementation using Frank. On this repository it says that it uses Dyfrig and that site redirects to Freya... 
Is Frank still a thing or is it now Freya?

**Comment by panesofglass** [comment]
Hi, @wallymathieu! This was intended to host several F# options. There is a Frank example in here, as well as Dyfrig. Dyfrig was rolled into Freya. Frank is still independent but has fallen behind. It wouldn't take much to update it and potentially get it back in shape as a useful, lightweight combinator library for `System.Net.Http` types for use in ASP.NET Web API or Azure Functions. Thoughts?

**Comment by wallymathieu** [comment]
Frank looks looks like significantly less code than other alternatives, so that's something.

**Comment by wallymathieu** [comment]
I think this question is answered. 😄
